config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :job_posts 
  #resources :applied_jobs
  # get 'job_posts/index'
  get '/search' , to: "job_posts#search"
  get '/show_applies/:id' , to: "job_posts#show_applies"
  get '/show_applies', to: "job_posts#show_applies"
  # get 'job_posts/new'
  # post 'job_posts/create'
  # get 'job_post/show'
  # get 'job_post/edit'
  # get 'job_post/update'
  # get 'job_post/destroy'
  # patch 'job_posts/update'
  get '/job_posts/:id/apply', to: "job_posts#apply", as: :apply

  # put '/job_posts/:id/apply', to: "job_posts#apply"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index" 
  get 'home/show'
  get 'home/search'

  resources :shortened_urls

  #post '/shortened_urls' , to: "shortened_urls#create"
end
 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    render
   end
end

app/views/home/index.html.erb
<div class = "tab">
  
  <% if user_signed_in? %> 
  <!--  <div class = "topnav">

      <%= link_to('Home', root_path)%>

      <%= link_to('Profile', '/home/show')%>
      <% if current_user.user_type == "contractor"%>
        <%= link_to('Create New Job Post', new_job_post_path)%>
      <% end %>
      
      <%= link_to('Show all Job posts', job_posts_path)%>
    
      <% if current_user.user_type == "worker"%>
        <%= link_to('My Applications', show_applies_path)%>
      <% end %>

      <%= link_to "All Tiny URLs", shortened_urls_path %>
      <%= link_to "Generate Tiny URL", new_shortened_url_path%>
    </div>

    -->

    <h1 class = "abc">Welcome to Be Found!</h1>
    <p class = "abc"><%= notice %></p>
    <div class = "abc"> Welcome <%= current_user.email %>....! </div><br> 
    
    <p class = "abc img profile" ><%= image_tag current_user.image.to_s, :size => "70x50" %></p>

    <!--<div class = "logout"><%= button_to "Sign out", destroy_user_session_path, method: :delete %></div><br> -->
    
  <% else %>
    <%= button_to "Sign in", new_user_session_path %> 
    <%= button_to "Sign in as Admin", new_admin_user_session_path %>
  <% end %>
</div>

app/views/home/show.html.erb
<div class = "tab">
<p class = "abc"><%= notice %></p>

<h1 class = "abc"> Your Profile</h1>

<p class = "abc img" ><strong>Profilepic:</strong><%= image_tag current_user.image.to_s, :size => "70x50" %></p>
<p class = "abc" ><strong>Name:</strong><%= current_user.user_name %></p>
<p class = "abc" ><strong>Email:</strong><%= current_user.email %></p>
<p class = "abc" ><strong>Contact:</strong><%= current_user.contact %></p>
<p class = "abc" ><strong>Address:</strong><%= current_user.address %></p>
<p class = "abc" ><strong>Qualifications:</strong><%= current_user.qualification %></p>

<div class = "abc" ><%= link_to 'Back', root_path%> | <%= link_to 'Edit', edit_user_registration_path(current_user) %></div>
</div>