config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :job_posts 
  #resources :applied_jobs
  # get 'job_posts/index'
  get '/search' , to: "job_posts#search"
  get '/show_applies/:id' , to: "job_posts#show_applies"
  get '/show_applies', to: "job_posts#show_applies"
  # get 'job_posts/new'
  # post 'job_posts/create'
  # get 'job_post/show'
  # get 'job_post/edit'
  # get 'job_post/update'
  # get 'job_post/destroy'
  # patch 'job_posts/update'
  get '/job_posts/:id/apply', to: "job_posts#apply", as: :apply

  # put '/job_posts/:id/apply', to: "job_posts#apply"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index" 
  get 'home/show'
  get 'home/search'

  resources :shortened_urls

  #post '/shortened_urls' , to: "shortened_urls#create"
end
 

app/models/job_post.rb
class JobPost < ApplicationRecord
	belongs_to :user
	belongs_to :category
  	has_many :applied_jobs
	validates :category_id, :job_role, :job_description, :vacancies, :salary, :qualification, presence: true
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
before_action :set_job_post, only: %i[show edit update destroy]
before_action :authenticate_user!
load_and_authorize_resource :except => [:apply, :show_applies]

  def index
  
    if current_user.user_type == "contractor"
      @job_posts = JobPost.where("user_id = ?", current_user.id)
      if @job_posts.empty?
        redirect_to root_path, notice: 'You have not created any job posts yet!'
      end
    else
      @job_posts = JobPost.all
    end
  end

  def search
    if current_user.user_type == "contractor"
      @job_posts = JobPost.where("category_id = ? AND user_id = ?",params[:category_id], current_user.id)
    else
      @job_posts = JobPost.where("category_id = ?",params[:category_id])
    end
    if @job_posts.empty?
      redirect_to job_posts_path, notice: 'There are no search results in this category!'
    end
  end

  def new
    @job_post = JobPost.new

  end

  def create
    params[:job_post][:user_id] = current_user.id
    @job_post = JobPost.new(job_post_params)
    if @job_post.save

      redirect_to root_path, notice: 'Your Job Post has been created successfully!'#{params[:id]}"
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show

  end

  def edit

  end

  def update
    
    if @job_post.update(job_post_params)
      redirect_to job_post_path(@job_post), notice: 'Your Job Post has been updated successfully!'
    else
      render :edit
    #   # render plain: "OK"
    end
  end

  def apply
    #render "job_application"
    if AppliedJob.where("job_post_id = ? AND user_id = ?", params[:id],current_user.id).exists? 
      redirect_to job_posts_path(@job_post), notice: 'You have already applied for this job!'

    else
      
      AppliedJob.create(user_id: current_user.id, job_post_id: params[:id])
      redirect_to job_posts_path(@job_post), notice: 'You have applied for this job successfully!'
    
    end
 
  end

  def show_applies
    
    if current_user.user_type == "contractor"

      @applied_jobs =  AppliedJob.joins(:job_post).where(job_posts: {user_id: current_user.id}) 
      
      @applications = @applied_jobs.where("job_post_id = ?", params[:id])
      
      if @applications.empty?
        
        redirect_to job_posts_path, notice: 'There are no job applications on this job post yet!'
      end
    else
      @applied_jobs = AppliedJob.where("user_id = ?",current_user.id)
      if @applied_jobs.empty?
        redirect_to root_path, notice: 'You have not applied for any job_post yet!'
      end
      #redirect_to job_posts_path
    end
  end

  def destroy
    @job_post.destroy
    #byebug
    redirect_to job_posts_path, notice: 'Job Post has been deleted successfully!'
  end

  private

  def job_post_params
    params.require(:job_post).permit( :job_role, :category_id,:job_description, :vacancies, :user_id, :salary, :qualification)
  end

  def set_job_post
    @job_post = JobPost.find(params[:id])
  end

end

app/helpers/job_post_helper.rb
module JobPostHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/views/job_posts/_form.html.erb
<%= form_for @job_post do |form| %>

  <% if @job_post.errors.any? %>
    <% @job_post.errors.full_messages.each do |message| %>
      <p class = "abc"><%= message %></p>
    <% end %>
  <% end %>

    <div class = "abc">
      <%= form.label :category_name %><br>
      <%= form.collection_select(:category_id, Category.all, :id, :category_name, :prompt => 'Select') %>
    </div>
    <div class = "abc">
      <%= form.label :job_role %><br>
      <%= form.text_field :job_role %>  
    </div>
    <div class = "abc">
      <%= form.label :job_description %><br>
      <%= form.text_area :job_description %>
    </div>    
    <div class = "abc">
      <%= form.label :vacancies %><br>
      <%= form.number_field :vacancies %>
    </div>   
    <div class = "abc">
      <%= form.label :salary %><br>
      <%= form.number_field :salary, min: 1000, max: 1000000 %>
    </div>
    <div class = "abc">
      <%= form.label :qualification %><br>
      <%= form.text_area :qualification %>  
    </div>
    <div class = "abc">
      <%= form.submit 'Submit Post' %><br>
    </div>
  </div>
</div>
<% end %>

app/views/job_posts/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/job_posts/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/job_posts/edit.html.erb
<div class = tab>
<h1 class = "abc">Edit Job Post</h1>
<%= render "form", job_post: @job_post %>
<div class = "abc" ><%= link_to 'Back', job_posts_path%> 
</div>

app/views/job_posts/index.html.erb
<div class= "tab">
  <p><%= notice %></p>

  <%= form_with url: "/search", method: :get do |form| %>
  <div class = "abc">
    <%= form.label :category_name, "Search for:" %>
        <%= form.collection_select(:category_id, Category.all, :id, :category_name, :prompt => 'Select') %>
    <%= form.submit "Search" %>
  </div>
  <% end %>

  <table border= '1'>
  <%= stylesheet_link_tag "main" %>
    <thead>
      <tr>
        <th class = "abc">Job Role </th><br>
        <th class = "abc">Job Description</th><br>
        <th class = "abc">Vacancies</th><br>
        <th class = "abc">Salary</th><br>
        <th class = "abc">Qualification</th><br>
      </tr>
    </thead> 
  
  
    <% if current_user.user_type == "contractor"%>
    	<% @job_posts.each do|job_post| %>
    	  <tbody>
    	    <tr>
            <td class = "abc"><%= job_post.job_role %></td>
            <td class = "abc"><%= job_post.job_description %></td>
            <td class = "abc"><%= job_post.vacancies %></td>
            <td class = "abc"><%= job_post.salary %></td>
            <td class = "abc"><%= job_post.qualification %></td>
            <td class = "abc"><%= link_to 'View', job_post %></td>
            <td class = "abc"><%= link_to 'Edit', edit_job_post_path(job_post) %></td>
            <td class = "abc"><%= link_to 'Delete', job_post_path(job_post), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" } %></td>
    	   
            <td class = "abc"><%= link_to 'Applications', "/show_applies/#{job_post.id}"%><br> 
          </tr>
    	  </tbody>
    	<% end %>
    <% else %>
    	<% @job_posts.each do|job_post| %>
    	  <tbody>
    	    <tr>
            <td class = "abc"><%= job_post.job_role %></td>
            <td class = "abc"><%= job_post.job_description %></td>
            <td class = "abc"><%= job_post.vacancies %></td>
            <td class = "abc"><%= job_post.salary %></td>
            <td class = "abc"><%= job_post.qualification %></td>
            <td class = "abc"><%= link_to 'View', job_post %></td>
            <td class = "abc"><%= link_to 'Apply', apply_path(job_post) %></td>
        	</tr>
        	</tbody>
    	<% end %>
		<% end %>
    <div class = "abc">
      <%= link_to 'Back', root_path%>
    </div>
  </table>
</div>

app/views/job_posts/new.html.erb
<div class = "tab">
<h1 class = "abc">New Job Post</h1>
<%= render "form", job_post: @job_post %>
<%= link_to 'Back', root_path%>
</div>

app/views/job_posts/search.html.erb
<div class = "tag">
<h1 class = "abc ">Search Results</h1>

  <table border= '1'>
  <%= stylesheet_link_tag "main" %>
    <thead>
      <tr>
        <th class = "abc">Job Role</th><br>
        <th class = "abc">Job Description</th><br>
        <th class = "abc">Vacancies</th><br>
        <th class = "abc">Salary</th><br>
        <th class = "abc">Qualification</th><br>
      </tr>
    </thead> 
  
  
    <% if current_user.user_type == "contractor"%>
    	<% @job_posts.each do|job_post| %>
    	  <tbody>
    	    <tr>
            <td class = "abc"><%= job_post.job_role %></td>
            <td class = "abc"><%= job_post.job_description %></td>
            <td class = "abc"><%= job_post.vacancies %></td>
            <td class = "abc"><%= job_post.salary %></td>
            <td class = "abc"><%= job_post.qualification %></td>
            <td class = "abc"><%= link_to 'View', job_post %></td>
            <td class = "abc"><%= link_to 'Edit', edit_job_post_path(job_post) %></td>
            <td class = "abc"><%= link_to 'Delete', job_post_path(job_post), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" } %></td>
    	    </tr>
    	  </tbody>
    	<% end %>
    <% else %>
    	<% @job_posts.each do|job_post| %>
    	  <tbody>
    	    <tr>
            <td class = "abc"><%= job_post.job_role %></td>
            <td class = "abc"><%= job_post.job_description %></td>
            <td class = "abc"><%= job_post.vacancies %></td>
            <td class = "abc"><%= job_post.salary %></td>
            <td class = "abc"><%= job_post.qualification %></td>
            <td class = "abc"><%= link_to 'View', job_post %></td>
            <td class = "abc"><%= link_to 'Apply', apply_path(job_post) %></td>

        	</tr>
        	</tbody>
    	<% end %>
		<% end %>
    <div class = "abc">
      <%= link_to 'Back', job_posts_path%>
    </div>
  </table>

</div>

app/views/job_posts/show.html.erb
<div class = "tab">
<p class = "abc"><%= notice %></p>

<h1 class = "abc"> Job Post :-</h1>

<p class = "abc" ><strong>Job Role:</strong><%= @job_post.job_role %></p>
<p class = "abc" ><strong>Job Description:</strong><%= @job_post.job_description %></p>
<p class = "abc" ><strong>Vacancies:</strong><%= @job_post.vacancies %></p>
<p class = "abc" ><strong>Salary:</strong><%= @job_post.salary %></p>
<p class = "abc" ><strong>Qualification:</strong><%= @job_post.qualification %></p>

<div class = "abc" ><%= link_to 'Back', job_posts_path%> </div>

app/views/job_posts/show_applies.html.erb
<div class = "tag">
<p class = "abc"><%= notice %></p>

<% if current_user.user_type == "contractor"%>
  <h1 class = "abc">Applications on Your Job Post:-</h1>

  <% @applications.each do|application| %>
  	<tbody>
  	  <tr>
        <div class = "abc"><strong>Applicant name : </strong><%= application.user.user_name %></div><br>
        <div class = "abc"><strong>Applicant email : </strong><%= application.user.email %></div><br>
        <div class = "abc"><strong>Applicant contact :  </strong><%= application.user.contact %></div><br>
        <div class = "abc"><strong>Applicant address : </strong><%= application.user.address %></div><br>
        <div class = "abc"><strong>Applicant Qualifications : </strong><%= application.user.qualification %></div><br><br>
  	  </tr>
  	</tbody>
  <% end %>
  <div class = "abc" ><%= link_to 'Back', job_posts_path%> </div>

<% else %>
  <h1 class = "abc">Your Job Applications:- </h1>

  <% @applied_jobs.each do|applied_job| %>
  	<tbody>
  	  <tr>
        <div class = "abc"><strong>Job role : </strong><%= applied_job.job_post.job_role %></div><br>
        <div class = "abc"><strong>Job description : </strong><%= applied_job.job_post.job_description %></div><br>
        <div class = "abc"><strong>Vacancies :  </strong><%= applied_job.job_post.vacancies %></div><br>
        <div class = "abc"><strong>Salary : </strong><%= applied_job.job_post.salary %></div><br>
        <div class = "abc"><strong>Qualifications : </strong><%= applied_job.job_post.qualification %></div>
  	    
        <h3 class = "abc">Contact Details:-</h3>
        
       
        <div class = "abc"><strong>Posted By : </strong><%= applied_job.job_post.user.user_name %></div><br>
        <div class = "abc"><strong>Email : </strong><%= applied_job.job_post.user.email %></div><br>
        <div class = "abc"><strong>Contact number : </strong><%= applied_job.job_post.user.contact %></div><br>
        <div class = "abc"><strong>Address : </strong><%= applied_job.job_post.user.address %></div><br><br>
        
        <h3>***********************************************</h3><br>

      </tr>
  	</tbody>
  <% end %>
  <div class = "abc" ><%= link_to 'Back', root_path%> </div>

<% end %>

app/views/job_posts/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>