config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :job_posts 
  #resources :applied_jobs
  # get 'job_posts/index'
  get '/search' , to: "job_posts#search"
  get '/show_applies/:id' , to: "job_posts#show_applies"
  get '/show_applies', to: "job_posts#show_applies"
  # get 'job_posts/new'
  # post 'job_posts/create'
  # get 'job_post/show'
  # get 'job_post/edit'
  # get 'job_post/update'
  # get 'job_post/destroy'
  # patch 'job_posts/update'
  get '/job_posts/:id/apply', to: "job_posts#apply", as: :apply

  # put '/job_posts/:id/apply', to: "job_posts#apply"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index" 
  get 'home/show'
  get 'home/search'

  resources :shortened_urls

  #post '/shortened_urls' , to: "shortened_urls#create"
end
 

app/models/shortened_url.rb
class ShortenedUrl < ApplicationRecord
validates :short_url, uniqueness: true
validates :original_url, presence: true
validates :original_url, uniqueness: true
before_validation :generate_short_url
  def generate_short_url
    loop do
      self.short_url = SecureRandom.urlsafe_base64(6)

      return true unless ShortenedUrl.exists?(short_url: self.short_url)
    end
  end
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  #before_action :authenticate_user!


  def index
    @shortened_urls = ShortenedUrl.all.order('created_at DESC')
  end
  
  def new
    @shortened_url = ShortenedUrl.new()
  end
  
  def create
    # params[:shortened_url][:original_url] = params[:original_url]
    @shortened_url = ShortenedUrl.new()
    @shortened_url = ShortenedUrl.new(shortened_url_params)
    # @original_url =ShortenedUrl.new() 
    #if @short_url.nil?
      #render :new,  status: :unprocessable_entity
    #else
    #@shortened_url.short_url = generate_short_url
    #@shortened_url.short_url = @short_url
    
    if @shortened_url.save
      render :show,  status: :created
    else
      render :new,  status: :unprocessable_entity, notice: 'Url already exists'
    end
  end 

  def show
    
    @shortened_url = ShortenedUrl.find_by_short_url(params[:id])
    #@shortened_url = ShortenedUrl.find(params[:id])
    #@shortened_url = ShortenedUrl.where("short_url = ?",(params[:id]))
    #@shortened_url = ShortenedUrl.where("id = ?",params[:id])
    #if @shortened_url
    
    if @shortened_url.original_url
       
      redirect_to @shortened_url.original_url,  allow_other_host: true
      @shortened_url.increment!(:click_count)
       
    else
      render file: "#{Rails.root}/public/404.html", status: :not_found
    end
  end

  def destroy
    
    ShortenedUrl.destroy(params[:id])
    #@shortened_url = ShortenedUrl.where("id = ?", params[:id])
    #@shortened_url.destroy
    #byebug
    redirect_to shortened_urls_path, notice: 'URL has been deleted successfully!'
  end

  private

  def shortened_url_params
    params.permit(:original_url)
    #params.require(:shortened_url).permit(:original_url)
  end

 end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/views/shortened_urls/index.html.erb
<div class = "tiny">
<p><%= notice %></p>

<div class = "abc" ><%= link_to 'Back', root_path%></div>

  <%#= link_to "Generate Tiny URL", new_shortened_url_path%>

  <%= form_with model: @shortened_url, url: shortened_urls_path do |form| %>
  <% if @shortened_url.present? %>
    <% if @shortened_url.errors.any? %>
      <% @shortened_url.errors.full_messages.each do |message| %>
        <p class = "abc"><%= message %></p>
      <% end %>
    <% end %>
  <% end %>
    <p><%#= notice %></p>

    <h2 class = "abc" >Generate your Tiny URL:-</h2>
    <p><%= notice %></p>

    <div class="field">
      <div class = "abc" ><%= form.label :original_url %></div>
      <%= form.text_field :original_url, placeholder: "Enter URL to be shortened" %>
    </div>

    <div class="actions">
      <%= form.submit "Shorten URL" %>
    </div>
  <% end %>


<h1 class = "abc" >All Shortened URLs</h1>

<table>
  <thead>
    <tr>
      <th class = "abc" >Original URL</th>
      <th CLASS = "abc" >Short URL</th>
      <th CLASS = "abc" >Click Count</th>
    </tr>
  </thead>
  <tbody>
    <% @shortened_urls.each do |shortened_url| %>
      <tr>
        <td class = "abc" ><%= shortened_url.original_url %></td>
        <td class = "abc" ><%= link_to shortened_url_url(shortened_url.short_url), shortened_url_url(shortened_url.short_url), target: "_blank" %></td>

      <!--  <td class = "abc" ><%#= link_to shortened_url.short_url, shortened_url_path(shortened_url.short_url), target: "_blank" %></td>
        <td class = "abc" ><%#= link_to shortened_url.short_url, shortened_url, target: "_blank" %></td> -->
        <td class = "abc" ><%= shortened_url.click_count %></td>
        <td class = "abc" ><%= link_to 'Delete', shortened_url_path(shortened_url), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" } %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/shortened_urls/new.html.erb
<%#= render "/shortened_urls/index", shortened_url: @shortened_url %>


<p><%= notice %></p>
<%= form_with model: @shortened_url, url: shortened_urls_path do |form| %>
  <% if @shortened_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shortened_url.errors.count, "error") %> prohibited this URL from being shortened:</h2>
      <ul>
      <% @shortened_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= notice %></p>

  <div class = "abc" ><%= link_to 'Back', root_path%></div>

  <h2 class = "abc" >Generate your Tiny URL:-</h2>
  <p><%= notice %></p>

  <div class="field">
    <div class = "abc" ><%= form.label :original_url %></div>
    <%= form.text_field :original_url, placeholder: "Enter URL to be shortened" %>
  </div>

  <div class="actions">
    <%= form.submit "Shorten URL" %>
  </div>
<% end %>

app/views/shortened_urls/show.html.erb
<div class = "abc" ><%#= link_to 'Back', root_path%></div>
<div class = "abc" ><%= link_to 'Back', root_path%></div>

<h3>Here's your shortened URL:</h3>

<p><%= link_to @shortened_url.short_url, shortened_url_path(@shortened_url.short_url), target: "_blank" %></p>